### ISSUE TITLE
[BUG]: magical of the magicgate

### ISSUE THREAD

**Issue by Sonic1paRadise** [987123879113/pcsx2#13]
### Describe the Bug

preparing the hard drive.......
[emulator crashes]

### Reproduction Steps

only try to use a utility disc

### PCSX2 Revision

non-official

### Operating System

Windows 10 (64bit)

### CPU

not required

### GPU

not required

### Logs & Dumps

[crash-2023-09-09-15-20-15-091.txt](https://github.com/987123879113/pcsx2/files/12565728/crash-2023-09-09-15-20-15-091.txt)
[crash-2023-09-09-15-22-06-373.txt](https://github.com/987123879113/pcsx2/files/12565729/crash-2023-09-09-15-22-06-373.txt)

**Comment by 987123879113** [comment]
If you don't intend on using the Python 2 functionality then I suggest using the `magicgate` branch here: https://github.com/987123879113/pcsx2/tree/magicgate

The usage changed slightly compared to the normal Python 2 version though. Your HDD ID should be included with the HDD image like so:
hdd.raw
hdd.raw.hddid

And your ILINK_ID.bin should go in the BIOS folder if you need it.

The code is built using a much more recent version of PCSX2 upstream but all of the Python 2-specific things have been removed because I just wanted something easy to maintain for basic work requiring magicgate stuff.

You can download a prebuilt version here: https://nightly.link/987123879113/pcsx2/workflows/windows_build_matrix/magicgate?status=completed

**Comment by Sonic1paRadise** [comment]
how do i create hdd id

**Comment by Sonic1paRadise** [comment]
another thing worth to denote, when booting into bios on magicgate fork, it
crashes

fr, 910. 2023 р. о 15:42 987123879113 ***@***.***> said:

**Comment by Sonic1paRadise** [comment]
aka it goes down
[crash-2023-10-11-20-08-14-757.dmp](https://github.com/987123879113/pcsx2/files/12872759/crash-2023-10-11-20-08-14-757.dmp)
[crash-2023-10-11-20-08-14-757.txt](https://github.com/987123879113/pcsx2/files/12872761/crash-2023-10-11-20-08-14-757.txt)

**Comment by 987123879113** [comment]
If you don't know what an HDD ID is then maybe you can just ignore it but I don't understand what your usecase is. It's the security section from an official Sony HDD and allows you to clone a specific HDD.

None of your dumps, both the original and the new ones, actually give me any useful information so I can't help you out.

**Comment by Sonic1paRadise** [comment]
I just tried to browse hdd using official dashboard

**Comment by 987123879113** [comment]
I was able to check the .dmp in Windbg today and you're crashing in the recompiler ([i5900.cpp:2386?](https://github.com/987123879113/pcsx2/blob/magicgate/pcsx2/x86/ix86-32/iR5900.cpp#L2386)). My fork doesn't touch the recompiler so I suspect this is something unrelated to MagicGate.

Download the corresponding nightly build of PCSX2 from upstream, it's the same commit I based the magicgate branch on just to be absolutely sure: https://github.com/PCSX2/pcsx2/releases/tag/v1.7.5048

If that still crashes on your system then it's a problem between PCSX2 and your system and not something I can/will fix.

**Comment by Sonic1paRadise** [comment]
It does not

**Comment by 987123879113** [comment]
That's strange. Based on your .dmp you were using pcsx2-qtx64.exe. Have you tried pcsx2-qtx64-clang.exe? Alternatively, instead of using the SSE4 build, have you tried the cmake and/or AVX2 builds? I think cmake's pcsx2-qtx64-clang.exe is closest to what is in the upstream release's zip.

**Comment by Sonic1paRadise** [comment]
I don’t have an avx2 cpu.
But I will try clang and cmake later on.
Until next email.
Please remain standby.
Cya!

**Comment by 987123879113** [comment]
I double checked how upstream makes their release ZIPs and it's definitely taking the EXE that is equivalent to PCSX2-windows-Qt-x64-cmake's pcsx2-qt-clang.exe. Since the build from upstream didn't crash then I think maybe your CPU just doesn't like some of the SSE4 instructions somewhere in the SSE4 build. Hope the cmake's clang build fixes things for you. :)

**Comment by Sonic1paRadise** [comment]
HOLY MOLY IT WORKS

**Comment by Sonic1paRadise** [comment]
hold up wait a minute
[crash-2023-10-13-19-06-39-940.dmp](https://github.com/987123879113/pcsx2/files/12895464/crash-2023-10-13-19-06-39-940.dmp)
[crash-2023-10-13-19-06-39-940.txt](https://github.com/987123879113/pcsx2/files/12895467/crash-2023-10-13-19-06-39-940.txt)

**Comment by 987123879113** [comment]
It looks like you're crashing in the same exact place in the recompiler still, during some memory access. You can try disabling the recompiler but it'll be really slow. At any rate, this seems like a PC-specific issue and none of the info provided so far has shown it's actually related to the MagicGate code so it's unlikely this can be fixed.

What are your PC's specs exactly anyway?

**Comment by AhayriSG** [comment]
Hi @987123879113,

I'm using the PCSX2 MagicGate branch to play my DVD-Video dumps, but I'm not getting any audio **during playback**. Is there a setting in the PCSX2 audio configuration that I might have misconfigured? Alternatively, could there be an option in the PS2 DVD Player menu that I'm overlooking to fix this audio "issue"? **Does MagicGate build simply not support audio playback?**

I haven't found any reports or information regarding the missing audio on the PCSX2 DVD movie request page(https://github.com/PCSX2/pcsx2/issues/1981).

Thanks.

**Comment by Sonic1paRadise** [comment]
that is not a magicgate related issue
